### ISSUE TITLE
Just started not working one day with this error

### ISSUE THREAD

**Issue by sumseq** [Phlya/adjustText#167]
I have been using this package a lot but recently it seems to have stopped working.
I am using a conda env so maybe its a new version of matplotlib that is messing it up?
The call I am using is:

```
adjust_text(texts3,` arrowprops=dict(arrowstyle='-', color='darkblue',lw=1.0), expand_points=(1.75,1.75), expand_text=(1.1,1.3),autoalign=True)
```

and the error is:

```
Traceback (most recent call last):
  File "./plot_masp_cr2144_med_timings_gtc.py", line 211, in <module>
    adjust_text(texts3, arrowprops=dict(arrowstyle='-', color='darkblue',lw=1.0), expand_points=(1.75,1.75), expand_text=(1.1,1.3),autoalign=True)
  File "/home/sumseq/Dropbox/Work/Conferences/2024_GTC/presentation/adjustText.py", line 588, in adjust_text
    arrowpatch = FancyArrowPatch(
  File "/home/sumseq/miniconda3/envs/psi/lib/python3.8/site-packages/matplotlib/_api/deprecation.py", line 454, in wrapper
    return func(*args, **kwargs)
  File "/home/sumseq/miniconda3/envs/psi/lib/python3.8/site-packages/matplotlib/patches.py", line 4123, in __init__
    super().__init__(**kwargs)
  File "/home/sumseq/miniconda3/envs/psi/lib/python3.8/site-packages/matplotlib/_api/deprecation.py", line 454, in wrapper
    return func(*args, **kwargs)
  File "/home/sumseq/miniconda3/envs/psi/lib/python3.8/site-packages/matplotlib/patches.py", line 100, in __init__
    self._internal_update(kwargs)
  File "/home/sumseq/miniconda3/envs/psi/lib/python3.8/site-packages/matplotlib/artist.py", line 1223, in _internal_update
    return self._update_props(
  File "/home/sumseq/miniconda3/envs/psi/lib/python3.8/site-packages/matplotlib/artist.py", line 1197, in _update_props
    raise AttributeError(
AttributeError: FancyArrowPatch.set() got an unexpected keyword argument 'expand_points'
```

**Comment by Phlya** [comment]
In the newly released version of adjustText there is no argument "expand_points" - there is just one "expand". I just realized the docs are not built correctly, but you can see the list of available arguments here:
https://github.com/Phlya/adjustText/blob/87a46ea91046b33b21547131209d08b076dedab5/adjustText/__init__.py#L341

**Comment by Phlya** [comment]
The docs are fixed now
https://adjusttext.readthedocs.io/en/latest/
