### ISSUE TITLE
3d: bug or missing feature?

### ISSUE THREAD

**Issue by gianpaolo-m** [Phlya/adjustText#72]
Hi,
thanks for your work!

The library does nothing with 3d scatter:
`ax.text(x, y,z)
...
adjust_text(texts)`

It's a bug or a missing feature?

**Comment by Phlya** [comment]
Hi!

Wow, I don't know, never tried that, but thanks for reporting! You can try this, might help: https://github.com/Phlya/adjustText/pull/64

**Comment by gianpaolo-m** [comment]
Replaced with the new `__init__.py`
No luck at first attempt:

```
Traceback (most recent call last):
       adjust_text(texts)
      File ".python\lib\site-packages\adjustText\__init__.py", line 507, in adjust_text     ax=ax)
      File ".python\lib\site-packages\adjustText\__init__.py", line 118, in optimally_align_text
      ax_bbox = ax.axesPatch.get_extents()
AttributeError: 'Axes3DSubplot' object has no attribute 'axesPatch'
```

**Comment by Phlya** [comment]
Oh I see... I have never worked with 3D plots, and seems like they behave a bit differently, I am sorry, I guess it won't work.
